# -*- coding: utf-8 -*-
"""Hashed Passwords

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKiUwbd7qUH4t6CLB0cQUU0m3-K5tnop
"""

from passlib.hash import bcrypt

def hash_password(password):
    # It's good practice to ensure the password is a string
    return bcrypt.hash(str(password))

# --- IMPORTANT: Run this script and copy the FULL HASH string ---

# Example 1: Your Mathura vet password
password_to_hash_vet = "testing"
hashed_password_vet = hash_password(password_to_hash_vet)
print(f"Original: '{password_to_hash_vet}'")
print(f"Hashed for druditjainvet@gmail.com: '{hashed_password_vet}'")
print("-" * 30)

